sudo: required

services:
  - docker
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: bash
      env:
        - ENV='localhost'

before_script:
  - docker-compose up -d

script:
  - npm i
  - npm run truffle:test
  - npm run truffle:migrate
  - npm run test
  - npm run test:report

after_script:
  - docker-compose down