version: '2'
services:

  testrpc:
    environment:
      - RPC_HOST=testrpc
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"

  ipfs:
    image: ipfs/go-ipfs
    ports:
     - "8080:8080"
     - "5001:5001"
     - "4001:4001"
    
